"""Default properties for every Qlik chart type. GENERATED - do not edit.

Produced by tools/generate_chart_specs.py from the nebula.js bundles
shipped with Qlik Sense itself, so these are the exact property trees
the Qlik client writes when you add a chart by hand. Guessing them from
documentation produced charts that rendered blank without erroring.

Each entry carries the property tree plus (min, max) dimensions and
measures the chart accepts - a scatter plot needs two measures, and
nothing short of the bundle would have told us that.

To refresh:
    node tools/extract_chart_specs.js > tools/chart_defaults.json
    python tools/generate_chart_specs.py
"""

CHART_DEFAULTS = {'barchart': {'bundle': 'sn-bar-chart',
              'dimensions': (0, 2),
              'measures': (1, 15),
              'properties': {'barGrouping': {'grouping': 'grouped'},
                             'color': {'auto': True,
                                       'autoMinMax': True,
                                       'dimensionScheme': '12',
                                       'expressionIsColor': True,
                                       'expressionLabel': '',
                                       'formatting': {'numFormatFromTemplate': True},
                                       'measureScheme': 'sg',
                                       'mode': 'primary',
                                       'paletteColor': {'index': 6},
                                       'persistent': False,
                                       'reverseScheme': False,
                                       'useBaseColors': 'off',
                                       'useDimColVal': True,
                                       'useMeasureGradient': True},
                             'components': [],
                             'dataPoint': {'showLabels': False,
                                           'showSegmentLabels': False,
                                           'showTotalLabels': True},
                             'dimensionAxis': {'axisDisplayMode': 'auto',
                                               'continuousAuto': True,
                                               'dock': 'near',
                                               'label': 'auto',
                                               'maxVisibleItems': 10,
                                               'show': 'all'},
                             'footnote': '',
                             'gridLine': {'auto': True, 'spacing': 2},
                             'legend': {'dock': 'auto',
                                        'show': True,
                                        'showTitle': True},
                             'measureAxis': {'autoMinMax': True,
                                             'dock': 'near',
                                             'max': 10,
                                             'min': 0,
                                             'minMax': 'min',
                                             'show': 'all',
                                             'spacing': 1},
                             'orientation': 'vertical',
                             'preferContinuousAxis': True,
                             'qHyperCubeDef': {'qDimensions': [],
                                               'qInitialDataFetch': [{'qHeight': 500,
                                                                      'qWidth': 17}],
                                               'qMeasures': [],
                                               'qSuppressMissing': True,
                                               'qSuppressZero': False},
                             'refLine': {'dimRefLines': [], 'refLines': []},
                             'scrollStartPos': 0,
                             'scrollbar': 'miniChart',
                             'showDetails': True,
                             'showDisclaimer': True,
                             'showMiniChartForContinuousAxis': True,
                             'showTitles': True,
                             'subtitle': '',
                             'title': '',
                             'tooltip': {'auto': True, 'data': {}, 'hideBasic': False},
                             'version': '2.2.0'},
              'version': '2.2.0'},
 'boxplot': {'bundle': 'sn-boxplot',
             'dimensions': (1, 2),
             'measures': (1, 1),
             'properties': {'boxplotDef': {'calculations': {'auto': True,
                                                            'mode': 'tukey',
                                                            'parameters': {'fractiles': 0.01,
                                                                           'stdDev': 3,
                                                                           'tukey': 1.5}},
                                           'color': {'auto': True,
                                                     'box': {'paletteColor': {'color': '#e6e6e6',
                                                                              'index': -1}},
                                                     'expressionIsColor': True,
                                                     'expressionLabel': '',
                                                     'mode': 'primary',
                                                     'point': {'paletteColor': {'color': '#4477aa',
                                                                                'index': 6}},
                                                     'useBaseColors': 'off'},
                                           'elements': {'boxEnd': {'expression': None,
                                                                   'name': ''},
                                                        'boxMiddle': {'expression': None,
                                                                      'name': ''},
                                                        'boxStart': {'expression': None,
                                                                     'name': ''},
                                                        'firstWhisker': {'expression': None,
                                                                         'name': ''},
                                                        'lastWhisker': {'expression': None,
                                                                        'name': ''},
                                                        'outliers': {'include': True,
                                                                     'sortOutliers': True}},
                                           'presentation': {'whiskers': {'show': True}},
                                           'qHyperCubeDef': {'qAlwaysFullyExpanded': True,
                                                             'qDimensions': [],
                                                             'qMeasures': [],
                                                             'qMode': 'S',
                                                             'qSuppressMissing': True,
                                                             'qSuppressZero': False},
                                           'sorting': {'autoSort': True}},
                            'dimensionAxis': {'dock': 'near',
                                              'label': 'auto',
                                              'show': 'all'},
                            'footnote': '',
                            'gridlines': {'auto': True, 'spacing': 2},
                            'measureAxis': {'autoMinMax': True,
                                            'dock': 'near',
                                            'max': 10,
                                            'min': 0,
                                            'minMax': 'min',
                                            'show': 'all',
                                            'spacing': 1},
                            'orientation': 'vertical',
                            'refLine': {'refLines': []},
                            'showTitles': True,
                            'sorting': {'autoSort': True,
                                        'elementId': 'firstWhisker',
                                        'sortCriteria': {'sortByAscii': 0,
                                                         'sortByExpression': 0,
                                                         'sortByNumeric': 0}},
                            'subtitle': '',
                            'title': '',
                            'version': '1.0.6'},
             'version': '1.0.6'},
 'bulletchart': {'bundle': 'sn-bullet-chart',
                 'dimensions': (0, 1),
                 'measures': (1, 15),
                 'properties': {'color': {'auto': True,
                                          'bar': {'index': 6},
                                          'mode': 'primary',
                                          'target': {'color': '#000000', 'index': -1}},
                                'dataPoint': {'showLabels': False,
                                              'showSegmentLabels': False,
                                              'showTotalLabels': True},
                                'dimensionAxis': {'dock': 'near',
                                                  'label': 'auto',
                                                  'show': 'all'},
                                'footnote': '',
                                'gridLine': {'auto': True, 'spacing': 2},
                                'measureAxis': {'commonAxis': False,
                                                'commonRange': False,
                                                'dock': 'near',
                                                'show': 'all',
                                                'spacing': 1},
                                'orientation': 'vertical',
                                'qHyperCubeDef': {'qDimensions': [],
                                                  'qInitialDataFetch': [{'qHeight': 500,
                                                                         'qWidth': 15}],
                                                  'qMeasures': [],
                                                  'qSuppressMissing': True,
                                                  'qSuppressZero': False},
                                'scrollStartPos': 0,
                                'scrollbar': 'bar',
                                'showDetails': True,
                                'showTitles': True,
                                'subtitle': '',
                                'title': '',
                                'tooltip': {'auto': True,
                                            'description': '',
                                            'hideBasic': False,
                                            'title': ''},
                                'version': '2.2.0'},
                 'version': '2.2.0'},
 'combochart': {'bundle': 'sn-combo-chart',
                'dimensions': (1, 1),
                'measures': (1, 15),
                'properties': {'barGrouping': {'grouping': 'grouped'},
                               'color': {'auto': True,
                                         'autoMinMax': True,
                                         'dimensionScheme': '12',
                                         'expressionIsColor': True,
                                         'expressionLabel': '',
                                         'measureMax': 10,
                                         'measureMin': 0,
                                         'measureScheme': 'sg',
                                         'mode': 'primary',
                                         'paletteColor': {'index': 6},
                                         'persistent': False,
                                         'reverseScheme': False,
                                         'useBaseColors': 'off',
                                         'useDimColVal': True,
                                         'useMeasureGradient': True},
                               'components': [],
                               'dataPoint': {'show': False,
                                             'showBarLabels': False,
                                             'showLineLabels': False},
                               'dimensionAxis': {'axisDisplayMode': 'auto',
                                                 'continuousAuto': True,
                                                 'dock': 'near',
                                                 'label': 'auto',
                                                 'maxVisibleItems': 10,
                                                 'show': 'all'},
                               'footnote': '',
                               'legend': {'dock': 'auto',
                                          'show': True,
                                          'showTitle': True},
                               'lineType': 'line',
                               'measureAxes': [{'autoMinMax': True,
                                                'dock': 'near',
                                                'max': 10,
                                                'min': 0,
                                                'minMax': 'min',
                                                'show': 'all',
                                                'spacing': 1},
                                               {'autoMinMax': True,
                                                'dock': 'far',
                                                'max': 10,
                                                'min': 0,
                                                'minMax': 'min',
                                                'show': 'all',
                                                'spacing': 1}],
                               'nullMode': 'gap',
                               'orientation': 'vertical',
                               'preferContinuousAxis': True,
                               'qHyperCubeDef': {'qAlwaysFullyExpanded': True,
                                                 'qDimensions': [],
                                                 'qInitialDataFetch': [{'qHeight': 500,
                                                                        'qWidth': 17}],
                                                 'qMeasures': [],
                                                 'qSuppressMissing': True,
                                                 'qSuppressZero': False},
                               'refLine': {'dimRefLines': [],
                                           'refLines': [],
                                           'refLines2': []},
                               'scrollStartPos': 0,
                               'separateStacking': True,
                               'showMiniChartForContinuousAxis': True,
                               'showTitles': True,
                               'stackedArea': False,
                               'subtitle': '',
                               'title': '',
                               'tooltip': {'auto': True,
                                           'description': '',
                                           'hideBasic': False,
                                           'title': ''},
                               'version': '1.38.0'},
                'version': '1.38.0'},
 'filterpane': {'bundle': 'sn-filter-pane',
                'dimensions': (1, 1000),
                'measures': (0, 0),
                'properties': {'footnote': '',
                               'qChildListDef': {},
                               'showDetails': True,
                               'showTitles': False,
                               'subtitle': '',
                               'title': '',
                               'version': '1.2.0'},
                'version': '1.2.0'},
 'gauge': {'bundle': 'sn-gauge',
           'dimensions': (0, 0),
           'measures': (1, 1),
           'properties': {'angle': 0.7,
                          'autoOrientation': True,
                          'color': {'useBaseColors': 'measure'},
                          'components': [],
                          'footnote': '',
                          'gaugetype': 'radial',
                          'measureAxis': {'max': 100,
                                          'min': 0,
                                          'show': 'all',
                                          'spacing': 1},
                          'orientation': 'horizontal',
                          'paletteProgressColor': {'index': 6},
                          'qHyperCubeDef': {'qInitialDataFetch': [{'qHeight': 1,
                                                                   'qWidth': 1}],
                                            'qMeasures': [],
                                            'qSuppressMissing': True,
                                            'qSuppressZero': False},
                          'refLine': {'refLines': []},
                          'segmentInfo': {'limits': [],
                                          'paletteColors': [{'index': 6}]},
                          'showDetails': True,
                          'showTitles': True,
                          'subtitle': '',
                          'title': '',
                          'useSegments': False,
                          'version': '0.8.13'},
           'version': '0.8.13'},
 'histogram': {'bundle': 'sn-histogram',
               'dimensions': (1, 1),
               'measures': (0, 0),
               'properties': {'bins': {'auto': True,
                                       'binCount': '',
                                       'binMode': 'maxCount',
                                       'binSize': 10,
                                       'countDistinct': False,
                                       'offset': 0},
                              'color': {'bar': {'paletteColor': {'color': '#4477aa',
                                                                 'index': 6}}},
                              'dataPoint': {'showLabels': False},
                              'dimensionAxis': {'dock': 'near',
                                                'label': 'auto',
                                                'show': 'all'},
                              'footnote': '',
                              'gridlines': {'auto': True, 'spacing': 2},
                              'measureAxis': {'autoMinMax': True,
                                              'dock': 'near',
                                              'label': '',
                                              'max': 10,
                                              'min': 0,
                                              'minMax': 'min',
                                              'show': 'all',
                                              'spacing': 1},
                              'qHyperCubeDef': {'qAlwaysFullyExpanded': True,
                                                'qDimensions': [],
                                                'qMeasures': [],
                                                'qMode': 'S',
                                                'qSuppressMissing': True,
                                                'qSuppressZero': False},
                              'refLine': {'refLines': []},
                              'showTitles': True,
                              'sorting': {'autoSort': True},
                              'subtitle': '',
                              'title': '',
                              'version': '1.0.6'},
               'version': '1.0.6'},
 'kpi': {'bundle': 'sn-kpi',
         'dimensions': (0, 0),
         'measures': (1, 2),
         'properties': {'components': [],
                        'disableNavMenu': True,
                        'fontSize': 'M',
                        'footnote': '',
                        'layoutBehavior': 'relative',
                        'openUrlInNewTab': True,
                        'qHyperCubeDef': {'qDimensions': [],
                                          'qInitialDataFetch': [{'qHeight': 10,
                                                                 'qWidth': 500}],
                                          'qMeasures': [],
                                          'qSuppressMeasureTotals': True,
                                          'qSuppressMissing': True,
                                          'qSuppressZero': False},
                        'sheetLink': '',
                        'showDetails': True,
                        'showMeasureTitle': True,
                        'showSecondMeasureTitle': True,
                        'showTitles': False,
                        'subtitle': '',
                        'textAlign': 'center',
                        'title': '',
                        'useLink': False,
                        'version': '2.4.0'},
         'version': '2.4.0'},
 'linechart': {'bundle': 'sn-line-chart',
               'dimensions': (1, 2),
               'measures': (1, 15),
               'properties': {'color': {'auto': True,
                                        'autoMinMax': True,
                                        'dimensionScheme': '12',
                                        'expressionIsColor': True,
                                        'expressionLabel': '',
                                        'formatting': {'numFormatFromTemplate': True},
                                        'measureScheme': 'sg',
                                        'mode': 'primary',
                                        'paletteColor': {'index': 6},
                                        'persistent': False,
                                        'reverseScheme': False,
                                        'useBaseColors': 'off',
                                        'useDimColVal': True,
                                        'useMeasureGradient': True},
                              'components': [],
                              'dataPoint': {'show': False, 'showLabels': False},
                              'dimensionAxis': {'axisDisplayMode': 'auto',
                                                'continuousAuto': True,
                                                'dock': 'near',
                                                'label': 'auto',
                                                'maxVisibleItems': 10,
                                                'show': 'all'},
                              'footnote': '',
                              'gridLine': {'auto': True, 'spacing': 2},
                              'legend': {'dock': 'auto',
                                         'show': True,
                                         'showTitle': True},
                              'lineType': 'line',
                              'measureAxis': {'autoMinMax': True,
                                              'dock': 'near',
                                              'logarithmic': False,
                                              'max': 10,
                                              'min': 0,
                                              'minMax': 'min',
                                              'show': 'all',
                                              'spacing': 1},
                              'nullMode': 'gap',
                              'orientation': 'horizontal',
                              'preferContinuousAxis': True,
                              'qHyperCubeDef': {'qAlwaysFullyExpanded': True,
                                                'qDimensions': [],
                                                'qDynamicScript': [],
                                                'qInitialDataFetch': [{'qHeight': 500,
                                                                       'qWidth': 17}],
                                                'qMeasures': [],
                                                'qSuppressMissing': True,
                                                'qSuppressZero': False},
                              'refLine': {'dimRefLines': [], 'refLines': []},
                              'scrollStartPos': 0,
                              'scrollbar': 'miniChart',
                              'separateStacking': True,
                              'showDetails': True,
                              'showDisclaimer': True,
                              'showMiniChartForContinuousAxis': True,
                              'showTitles': True,
                              'stackedArea': False,
                              'subtitle': '',
                              'title': '',
                              'tooltip': {'auto': True,
                                          'description': '',
                                          'hideBasic': False,
                                          'title': ''},
                              'version': '2.2.0'},
               'version': '2.2.0'},
 'mekkochart': {'bundle': 'sn-mekko-chart',
                'dimensions': (2, 2),
                'measures': (1, 1),
                'properties': {'cellColor': {'legend': {'show': 'auto',
                                                        'showTitle': True},
                                             'mode': 'auto'},
                               'footnote': '',
                               'qHyperCubeDef': {'qInitialDataFetch': [{'qHeight': 3333,
                                                                        'qWidth': 3}],
                                                 'qSuppressMissing': True,
                                                 'qSuppressZero': True},
                               'showTitles': True,
                               'subtitle': '',
                               'title': '',
                               'version': '1.4.7'},
                'version': '1.4.7'},
 'piechart': {'bundle': 'sn-pie-chart',
              'dimensions': (1, 1),
              'measures': (1, 2),
              'properties': {'color': {'auto': True,
                                       'autoMinMax': True,
                                       'dimensionScheme': '12',
                                       'expressionIsColor': True,
                                       'expressionLabel': '',
                                       'formatting': {'numFormatFromTemplate': True},
                                       'measureScheme': 'sg',
                                       'mode': 'primary',
                                       'paletteColor': {'index': 6},
                                       'persistent': False,
                                       'reverseScheme': False,
                                       'useBaseColors': 'off',
                                       'useDimColVal': True,
                                       'useMeasureGradient': True},
                             'components': [{'key': 'slices',
                                             'style': {'cornerRadius': 0,
                                                       'innerRadius': 0.55,
                                                       'strokeColor': {'color': '#FFFFFF',
                                                                       'index': -1},
                                                       'strokeWidth': 'none'}}],
                             'dataPoint': {'auto': True,
                                           'labelMode': 'share',
                                           'labelValueMode': 'arc'},
                             'dimensionTitle': False,
                             'donut': {'showAsDonut': False},
                             'footnote': '',
                             'legend': {'dock': 'auto',
                                        'show': False,
                                        'showTitle': True},
                             'qHyperCubeDef': {'qDimensions': [],
                                               'qInitialDataFetch': [{'qHeight': 500,
                                                                      'qWidth': 10}],
                                               'qMeasures': [],
                                               'qMode': 'S',
                                               'qSuppressMissing': True,
                                               'qSuppressZero': False},
                             'showDetails': True,
                             'showDisclaimer': True,
                             'showTitles': True,
                             'subtitle': '',
                             'title': '',
                             'tooltip': {'auto': True, 'data': {}, 'hideBasic': False},
                             'version': '2.3.0'},
              'version': '2.3.0'},
 'qlik-funnel-chart-ext': {'bundle': 'sn-funnel-chart',
                           'dimensions': (1, 1),
                           'measures': (1, 1),
                           'properties': {'color': {'auto': True,
                                                    'autoMinMax': True,
                                                    'dimensionScheme': '12',
                                                    'expressionIsColor': True,
                                                    'expressionLabel': '',
                                                    'measureScheme': 'sg',
                                                    'mode': 'primary',
                                                    'paletteColor': {'index': 6},
                                                    'persistent': False,
                                                    'reverseScheme': False,
                                                    'useBaseColors': 'off',
                                                    'useDimColVal': True,
                                                    'useMeasureGradient': True},
                                          'dataPoint': {'auto': True,
                                                        'labelMode': 'share'},
                                          'footnote': '',
                                          'funnel': {'mode': 'WIDTH'},
                                          'qHyperCubeDef': {'qDimensions': [],
                                                            'qInitialDataFetch': [{'qHeight': 5000,
                                                                                   'qWidth': 2}],
                                                            'qInterColumnSortOrder': [],
                                                            'qMeasures': [],
                                                            'qSuppressMissing': True,
                                                            'qSuppressZero': False},
                                          'showDimensionTitle': True,
                                          'showTitles': True,
                                          'subtitle': '',
                                          'title': '',
                                          'version': '1.12.0'},
                           'version': '1.12.0'},
 'qlik-network-chart': {'bundle': 'sn-network-chart',
                        'dimensions': (3, 4),
                        'measures': (0, 3),
                        'properties': {'displayEdgeLabel': False,
                                       'edgeType': 'dynamic',
                                       'footnote': '',
                                       'nodeShape': 'dot',
                                       'posEdgeLabel': 'top',
                                       'qHyperCubeDef': {'qDimensions': [],
                                                         'qInitialDataFetch': [{'qHeight': 1400,
                                                                                'qWidth': 7}],
                                                         'qMeasures': []},
                                       'shadowMode': False,
                                       'showTitles': False,
                                       'subtitle': '',
                                       'title': '',
                                       'version': '1.0.7'},
                        'version': '1.0.7'},
 'qlik-sankey-chart-ext': {'bundle': 'sn-sankey-chart',
                           'dimensions': (2, 5),
                           'measures': (1, 1),
                           'properties': {'footnote': '',
                                          'link': {'color': 3,
                                                   'colorBy': 'custom',
                                                   'opacity': 0.5,
                                                   'shadow': False},
                                          'node': {'padding': 0.2, 'width': 0.2},
                                          'qHyperCubeDef': {'qDimensions': [],
                                                            'qInitialDataFetch': [{'qHeight': 1666,
                                                                                   'qWidth': 6}],
                                                            'qMeasures': [],
                                                            'qSuppressMissing': True,
                                                            'qSuppressZero': False},
                                          'showTitles': True,
                                          'subtitle': '',
                                          'title': '',
                                          'version': '1.13.0'},
                           'version': '1.13.0'},
 'qlik-word-cloud': {'bundle': 'sn-word-cloud',
                     'dimensions': (1, 1),
                     'measures': (1, 1),
                     'properties': {'MaxSize': 100,
                                    'MinSize': 20,
                                    'Orientations': 2,
                                    'RadEnd': 90,
                                    'RadStart': -90,
                                    'Scale': 'linear',
                                    'ScaleColor': ['#FEE391',
                                                   '#FEC44F',
                                                   '#FE9929',
                                                   '#EC7014',
                                                   '#CC4C02',
                                                   '#993404',
                                                   '#662506'],
                                    'customRange': False,
                                    'customRangeFrom': {'color': '#4477aa',
                                                        'index': -1},
                                    'customRangeTo': {'color': '#ffcf02', 'index': -1},
                                    'qHyperCubeDef': {'qDimensions': [],
                                                      'qInitialDataFetch': [{'qHeight': 100,
                                                                             'qWidth': 2}],
                                                      'qMeasures': []},
                                    'version': '1.0.8'},
                     'version': '1.0.8'},
 'scatterplot': {'bundle': 'sn-scatter-plot',
                 'dimensions': (1, 1),
                 'measures': (2, 3),
                 'properties': {'color': {'auto': True,
                                          'autoMinMax': True,
                                          'dimensionScheme': '12',
                                          'expressionIsColor': True,
                                          'expressionLabel': '',
                                          'formatting': {'numFormatFromTemplate': True},
                                          'measureMax': 10,
                                          'measureMin': 0,
                                          'measureScheme': 'sg',
                                          'mode': 'primary',
                                          'paletteColor': {'index': 6},
                                          'persistent': False,
                                          'reverseScheme': False,
                                          'useBaseColors': 'off',
                                          'useDimColVal': True,
                                          'useMeasureGradient': True},
                                'components': [],
                                'dataPoint': {'bubbleSizes': 5,
                                              'compressionResolution': 5,
                                              'rangeBubbleSizes': [2, 8]},
                                'disableNavMenu': False,
                                'footnote': '',
                                'gridLine': {'auto': True, 'spacing': 2},
                                'labels': {'mode': 1},
                                'legend': {'dock': 'auto',
                                           'show': True,
                                           'showTitle': True},
                                'maxVisibleBubbles': 2500,
                                'navigation': False,
                                'qHyperCubeDef': {'qDimensions': [],
                                                  'qMeasures': [],
                                                  'qSuppressMissing': True},
                                'refLine': {'refLinesX': [], 'refLinesY': []},
                                'showDetails': False,
                                'showDisclaimer': True,
                                'showTitles': True,
                                'subtitle': '',
                                'title': '',
                                'tooltip': {'auto': True,
                                            'description': '',
                                            'hideBasic': False,
                                            'title': ''},
                                'trendLines': [],
                                'version': '3.60.0',
                                'xAxis': {'autoMinMax': True,
                                          'dock': 'near',
                                          'max': 10,
                                          'min': 0,
                                          'minMax': 'min',
                                          'show': 'all',
                                          'spacing': 1},
                                'yAxis': {'autoMinMax': True,
                                          'dock': 'near',
                                          'max': 10,
                                          'min': 0,
                                          'minMax': 'min',
                                          'show': 'all',
                                          'spacing': 1}},
                 'version': '3.60.0'},
 'sn-grid-chart': {'bundle': 'sn-grid-chart',
                   'dimensions': (2, 2),
                   'measures': (1, 1),
                   'properties': {'color': {'auto': True,
                                            'autoMinMax': True,
                                            'dimensionScheme': '12',
                                            'expressionIsColor': True,
                                            'expressionLabel': '',
                                            'measureScheme': 'sg',
                                            'mode': 'primary',
                                            'paletteColor': {'index': 6},
                                            'reverseScheme': False,
                                            'useBaseColors': 'off',
                                            'useDimColVal': True,
                                            'useMeasureGradient': True},
                                  'dataPoint': {'rangeBubbleSizes': [0.15, 0.4],
                                                'showLabels': 'off',
                                                'symbol': 'circle'},
                                  'footnote': '',
                                  'mode': 'default',
                                  'qHyperCubeDef': {'qAlwaysFullyExpanded': True,
                                                    'qDimensions': [],
                                                    'qMeasures': [],
                                                    'qMode': 'T',
                                                    'qSuppressMissing': True,
                                                    'qSuppressZero': False},
                                  'showDetails': True,
                                  'showTitles': True,
                                  'subtitle': '',
                                  'title': '',
                                  'version': '2.2.0',
                                  'xAxis': {'axisDisplayMode': 'auto',
                                            'dock': 'near',
                                            'gridLines': False,
                                            'label': 'auto',
                                            'maxVisibleItems': 10,
                                            'show': 'all'},
                                  'yAxis': {'axisDisplayMode': 'auto',
                                            'dock': 'near',
                                            'gridLines': False,
                                            'maxVisibleItems': 10,
                                            'show': 'all'}},
                   'version': '2.2.0'},
 'sn-org-chart': {'bundle': 'sn-org-chart',
                  'dimensions': (2, 2),
                  'measures': (0, 1),
                  'properties': {'components': [],
                                 'footnote': '',
                                 'navigationMode': 'free',
                                 'qHyperCubeDef': {'qDimensions': [],
                                                   'qInitialDataFetch': [{'qHeight': 500,
                                                                          'qWidth': 5}],
                                                   'qMeasures': [],
                                                   'qSuppressMissing': True,
                                                   'qSuppressZero': False},
                                 'resizeOnExpand': False,
                                 'showTitles': True,
                                 'style': {'backgroundColor': {'color': {'color': '#ffffff',
                                                                         'index': -1},
                                                               'colorExpression': '',
                                                               'colorType': 'colorPicker'},
                                           'border': {'color': {'color': '#737373',
                                                                'index': -1},
                                                      'colorExpression': '',
                                                      'colorType': 'auto',
                                                      'fullBorder': True,
                                                      'top': True},
                                           'fontColor': {'color': {'color': '#484848',
                                                                   'index': -1},
                                                         'colorExpression': '',
                                                         'colorType': 'auto'}},
                                 'subtitle': '',
                                 'title': ''},
                  'version': '1.4.2'},
 'sn-pivot-table': {'bundle': 'sn-pivot-table',
                    'dimensions': (1, 1000),
                    'measures': (1, 1000),
                    'properties': {'components': [],
                                   'footnote': '',
                                   'nullValueRepresentation': {'text': '-'},
                                   'qHyperCubeDef': {'qAlwaysFullyExpanded': False,
                                                     'qDimensions': [],
                                                     'qIndentMode': False,
                                                     'qInitialDataFetch': [{'qHeight': 50,
                                                                            'qLeft': 0,
                                                                            'qTop': 0,
                                                                            'qWidth': 50}],
                                                     'qMeasures': [],
                                                     'qMode': 'P',
                                                     'qShowTotalsAbove': True,
                                                     'qSuppressMissing': True,
                                                     'qSuppressZero': False},
                                   'showTitles': True,
                                   'subtitle': '',
                                   'title': '',
                                   'version': '7.17.0'},
                    'version': '7.17.0'},
 'sn-table': {'bundle': 'sn-table',
              'dimensions': (0, 1000),
              'measures': (0, 1000),
              'properties': {'components': [],
                             'enableChartExploration': False,
                             'footnote': '',
                             'qHyperCubeDef': {'qColumnOrder': [],
                                               'qDimensions': [],
                                               'qInitialDataFetch': [{'qHeight': 100,
                                                                      'qWidth': 50}],
                                               'qMeasures': []},
                             'showTitles': True,
                             'subtitle': '',
                             'title': '',
                             'totals': {'position': 'noTotals', 'show': True},
                             'usePagination': False,
                             'version': '6.19.0'},
              'version': '6.19.0'},
 'treemap': {'bundle': 'sn-treemap',
             'dimensions': (1, 15),
             'measures': (1, 1),
             'properties': {'color': {'auto': True,
                                      'autoMinMax': True,
                                      'dimensionScheme': '12',
                                      'expressionIsColor': True,
                                      'expressionLabel': '',
                                      'formatting': {'numFormatFromTemplate': True},
                                      'measureMax': 10,
                                      'measureMin': 0,
                                      'measureScheme': 'sg',
                                      'mode': 'primary',
                                      'paletteColor': {'index': 6},
                                      'persistent': False,
                                      'reverseScheme': False,
                                      'useBaseColors': 'off',
                                      'useDimColVal': True,
                                      'useMeasureGradient': True},
                            'footnote': '',
                            'labels': {'auto': True,
                                       'headers': True,
                                       'leaves': True,
                                       'overlay': True,
                                       'values': False},
                            'legend': {'dock': 'auto',
                                       'show': False,
                                       'showTitle': True},
                            'qHyperCubeDef': {'qAlwaysFullyExpanded': True,
                                              'qDimensions': [],
                                              'qIndentMode': True,
                                              'qInitialDataFetch': [{'qHeight': 3000,
                                                                     'qLeft': 0,
                                                                     'qTop': 0,
                                                                     'qWidth': 30}],
                                              'qMaxStackedCells': 3000,
                                              'qMeasures': [],
                                              'qMode': 'K',
                                              'qNoOfLeftDims': -1,
                                              'qShowTotalsAbove': True,
                                              'qSortbyYValue': -1,
                                              'qSuppressMissing': True,
                                              'qSuppressZero': False},
                            'showDetails': True,
                            'showDisclaimer': True,
                            'showTitles': True,
                            'subtitle': '',
                            'title': '',
                            'tooltip': {'auto': True,
                                        'description': '',
                                        'hideBasic': False,
                                        'title': ''},
                            'version': '1.7.2'},
             'version': '1.7.2'},
 'waterfallchart': {'bundle': 'sn-waterfall',
                    'dimensions': (0, 0),
                    'measures': (1, 50),
                    'properties': {'color': {'auto': True,
                                             'negativeValue': {'paletteColor': {'color': '#cc6677',
                                                                                'index': -1}},
                                             'positiveValue': {'paletteColor': {'color': None,
                                                                                'index': 6}},
                                             'subtotal': {'paletteColor': {'color': '#c3c3c3',
                                                                           'index': -1}}},
                                   'dataPoint': {'showLabels': True},
                                   'dimensionAxis': {'dock': 'near',
                                                     'label': 'auto',
                                                     'show': 'labels'},
                                   'footnote': '',
                                   'gridlines': {'auto': True, 'spacing': 2},
                                   'legend': {'dock': 'auto', 'show': True},
                                   'measureAxis': {'autoMinMax': True,
                                                   'dock': 'near',
                                                   'max': 10,
                                                   'min': 0,
                                                   'minMax': 'min',
                                                   'show': 'labels',
                                                   'spacing': 1},
                                   'qDef': {'isCustomFormatted': False,
                                            'numFormatFromTemplate': True,
                                            'qNumFormat': {}},
                                   'qHyperCubeDef': {'qDimensions': [],
                                                     'qInitialDataFetch': [{'qHeight': 10,
                                                                            'qWidth': 200}],
                                                     'qMeasures': [],
                                                     'qMode': 'S',
                                                     'qSuppressMissing': True},
                                   'refLine': {'refLines': []},
                                   'showTitles': True,
                                   'subtitle': '',
                                   'title': '',
                                   'version': '1.0.6'},
                    'version': '1.0.6'}}
